package rut.miit.testingsystem.exception;

public class UserNotFoundException extends RuntimeException {
}
